version: '3'

services:
  notifications_api:
    build:
      context: ../notifications_api
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq

  notifications_service:
    build:
      context: ../notifications_service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - EMAIL_GMAIL_USERNAME=
      - EMAIL_GMAIL_PASSWORD=

  nginx:
    build: ../nginx
    depends_on:
      - notifications_api
      - admin

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq

  admin:
    container_name: 'notification-admin'
    build: ../admin
    env_file:
      - ../admin/.env
    entrypoint:
      "entrypoint.sh"
    depends_on:
      - db
    ports:
      - '8000:8000'


  db:
    image: postgres:13.0-alpine
    container_name: 'notification-db'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../admin/.env
    ports:
      - '5432:5432'

volumes:
  postgres_data:
