version: '3'

services:
  notifications_api:
    build:
      context: ../notifications_api
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq

  nginx:
    build: ../nginx
    depends_on:
      - notifications_api

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
