# Generated by Django 4.1 on 2022-08-27 01:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('common', 'Обычное письмо'), ('personal_statistic', 'Персональная статистика')], max_length=50, verbose_name='Тип')),
                ('template', ckeditor.fields.RichTextField(verbose_name='Шаблон')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Тема')),
                ('channel', models.TextField(choices=[('email', 'email'), ('sms', 'sms')], max_length=8, verbose_name='Cпособ передачи')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='MailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Ожидает отправки'), ('done', 'Отправлено'), ('cancelled', 'Отменено')], default='waiting', max_length=250)),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='low', max_length=250)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('execution_datetime', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.template')),
            ],
            options={
                'verbose_name': 'Задача на рассылку',
                'verbose_name_plural': 'Задачи на рассылку',
            },
        ),
    ]
