# Generated by Django 4.0.7 on 2022-09-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_add_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtask',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает отправки'), ('processing', 'В процессе отправки'), ('done', 'Отправлено'), ('cancelled', 'Отменено')], default='waiting', max_length=250),
        ),
    ]
