# Generated by Django 4.0.7 on 2022-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_add_status_processing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryusers',
            options={'verbose_name': 'Категория пользователей', 'verbose_name_plural': 'Категории пользователей'},
        ),
        migrations.AddField(
            model_name='mailtask',
            name='lifetime_hours',
            field=models.IntegerField(default=1, verbose_name='Актуальность сообщения'),
        ),
    ]
