# Generated by Django 4.0.7 on 2022-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_add_lifetime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryusers',
            name='category_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
